//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockChainConference.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizer
    {
        public Organizer()
        {
            this.Event = new HashSet<Event>();
        }
    
        public int Id { get; set; }
        public string Lastname { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Fullname { get
            {
                return Lastname + " " + Name + " " + Surname;
            } }
        public string Email { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string CountryId { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
        public int GenderId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Event> Event { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
